# 额外配置选项，普通用户无需关注

# 是否检查更新
check_update_on_start = true

# 是否允许主界面缩放（界面实际布局是固定大小的）
main_window_resizable = false

# 最大存档数
max_save_count = 1000

####################以上所有配置修改后需要重新启动才能生效########################
####################以下所有配置修改后将立即生效########################

# 是否在点击读取存档按钮时关闭结果窗口（若存在）
destroy_result_windows_when_click_load_checklist_button = true

# 是否需要额外将输出结果导出为excel文件
[export_result_as_excel]
# 启用导出excel功能
enable = false
# 导出的文件名
export_file_name = "排行结果.xlsx"
# 导出前N名
export_rank_count = 1000

# 一些需要特殊补正的数据
[data_fixup]
# 由于词条[所有职业Lv1~30全部主动技能Lv+X（特性技能除外）]不能直接对应输出职业的1-45主动技能,需要打个折,可以自行配置折扣率
extra_all_job_all_active_skill_lv_1_30_deal_1_45_rate = 0.8

# 20s打桩数据
[20s_damage]
# 是否显示预估的20s打桩数据
enable = true
# 默认的分数与打桩的比例关系
score_to_damage_rate = "1 / 1077.97 * 3320" # 本人召唤在分数为107797%时，修炼场20s的伤害为3320e，先以这个为准给一版供参考的伤害值

# 设定存档对应的分数与打桩的比例关系，若下列数组中配置了当前存档的打桩系数，则会使用该系数，否则使用默认的打桩系数
# 可自行参照下面两个示例添加或删除配置
[[20s_damage.save_name_configs]]
save_name = "示例存档名1"
score_to_damage_rate = "1 / 1077.97 * 6666" # 第二个数字为你当前装备在结果界面显示的分数/100，如显示为107797%，则这里填1077.97，第三个数字泽天你用这套装备的20s打桩数据（以亿为单位）

[[20s_damage.save_name_configs]]
save_name = "示例存档名2"
score_to_damage_rate = "1 / 1077.97 * 8888" # 第二个数字为你当前装备在结果界面显示的分数/100，如显示为107797%，则这里填1077.97，第三个数字泽天你用这套装备的20s打桩数据（以亿为单位）

# 一些初始值
[initital_data]
# 啥也不穿的满级奶爸的体力与精神
physical_and_mental = "2674"
# 啥也不穿的满级奶妈和奶萝的智力
intelligence = "2400 - 33"

# 一些常量
[const]
## 奶爸
# 多少体精折合一级祝福
naiba_physical_and_mental_divisor = 630

## 奶妈
# 多少智力折合一级祝福
naima_intelligence_divisor = 675
# 唱歌倍率的一些系数：sing_song_increase_rate = naima_sing_song_increase_rate_base + naima_sing_song_increase_rate_amplification_coef * base_array[index_buf_amplification]
naima_sing_song_increase_rate_base = 1.25
naima_sing_song_increase_rate_amplification_coef = 0.05

## 奶萝
# 多少智力折合一级祝福
nailuo_intelligence_divisor = 665
# # 唱歌倍率的一些系数：sing_song_increase_rate = (nailuo_sing_song_increase_rate_base + nailuo_sing_song_increase_rate_amplification_coef * base_array[index_buf_amplification]) * nailuo_sing_song_increase_rate_final_coef
nailuo_sing_song_increase_rate_base = 1.20
nailuo_sing_song_increase_rate_amplification_coef = 0.05
nailuo_sing_song_increase_rate_final_coef = 1.20